add_compile_options(-Wno-c++98-compat)
add_compile_options(-Wno-c++98-compat-pedantic)
add_compile_options(-Wno-format-nonliteral)
add_compile_options(-Wno-extra-semi-stmt)
add_compile_options(-Wno-c99-extensions)
add_compile_options(-Wno-gnu-anonymous-struct)
add_compile_options(-Wno-missing-prototypes)
add_compile_options(-Wno-covered-switch-default)
add_compile_options(-Wno-reserved-identifier)
add_compile_options(-Wno-missing-variable-declarations)

add_compile_options(-fdiagnostics-color=always)
add_compile_options(-fms-extensions)
