name: Lint

on: [push]

env:
  NODE_VERSION: 20

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: corepack enable
      - run: corepack prepare
      - run: pnpm install

      - run: pnpm lint
      - run: pnpm prettier --check .
  clang-format-check:
    name: clang-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install clang-format
      - run: ls -a
      - run: pwd
      - run: |
          chmod +x ./.github/scripts/clang-format-check-recursive.sh
          ./.github/scripts/clang-format-check-recursive.sh
